---
kind: pipeline
name: default

platform:
  os: linux
  arch: amd64

steps:
  - name: go-build
    image: golang:alpine
    environment:
      CGO_ENABLED: "0"
    commands:
      - apk add -U --no-cache ca-certificates git binutils
      - go build .

  - name: build-staging
    image: plugins/docker
    settings:
      repo: bitsbeats/drone-git-update-fork
      auto_tag: true
      tags: latest
      username:
        from_secret: docker_user
      password:
        from_secret: docker_pass
    when:
      event:
        - tag
